version: '3.7'

services:
  classification:
    build: ./classification
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./classification/:/app/
    ports:
      - 8001:8000


  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./nginx_config.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - classification