stages:
  train_eval:
    cmd: python train_eval.py
    deps:
    - ../data/train.csv
    - train_eval.py
    outs:
    - model_artifacts/args.pt
    - model_artifacts/model_best.pt
    - model_artifacts/test_labels.txt
    - model_artifacts/test_labels_gold.txt
    - model_artifacts/test_labels_pred.txt
    - model_artifacts/test_labels_prob_pred.txt
    params:
    - params.yaml:
    metrics:
    - model_artifacts/test_pr_values.csv
  test:
    cmd: python test.py
    deps:
    - ../data/test.csv
    - model_artifacts/args.pt
    - model_artifacts/model_best.pt
    - test.py
    metrics:
    - test_results/test_metrics.json
