seed: 1111
max_epochs: 10
batch_size: 16
num_workers: 2
lr: 0.00003
lr_patience: 1
lr_factor: 0.5
es_patience: 3
gradient_accumulation_steps: 8
tunning_metric: "Recall"
loss_type: weighted_ce
use_fp16: True
label_smoothing: 0.2
hidden_size: 768
max_length: 512
class_threshold: 0.5

# Model selection
model_path: "google/muril-base-cased"

# Dataset params
task_name: "hate_speech_binary_classification"
labels: ['Non-Hate-Speech', 'Hate-Speech']